# Site settings
title: Liatrio
subtitle: DevOps by Culture, Tools, Process
email: contact@liatrio.com
description: As software drives most customer experiences today, businesses are constantly building and updating their applications to meet customer expectations. To do this successfully, many businesses are adopting DevOps, an approach that unites development and IT operations teams to automate development and deployment. The result? Continuous and successful software releases that deliver value to the customer.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://matthewpdias.github.io" # the base hostname & protocol for your site
author: Matthew Dias & Shane MacBride
street_address: 1234 Somewhere Road
city: Chico
state: CA
zip_code:
country: United States of America
phone: (555) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
